[project]
name = "chemberta_poc"
version = "0.1.0"
description = "Proof of Concept for ChemBERTaDNN"
authors = ["Ana Marta Sequeira"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.10.*"
numpy = "1.24.*"
scipy = "1.10.*"
scikit-learn = "1.2.*"
pandas = "2.0.*"
transformers = ">=4.55.4,<5"
redun = ">=0.22.0,<0.23"
pyarrow = ">=13.0.0,<14"
wandb = ">=0.17.3,<0.18"
s3fs = "*"
[pypi-dependencies]
torch = ">=2.6"