[project]
authors = ["Tomasz Danel <tomek@insitro.com>", "Benson Chen <bensonc@insitro.com>"]
channels = ["conda-forge", "nvidia"]
description = "KinDEL: DNA-Encoded Library Dataset For Kinase Inhibitors"
name = "kindel"
platforms = ["linux-64"]
version = "1.0.0"
license-file = "LICENSE.md"

[tasks]

[dependencies]
python = "3.10"
redun = ">=0.22.0,<0.23"
pandas = ">=2.2.3,<3"
rdkit = ">=2023.9.5,<2024"
tqdm = ">=4.66.5,<5"
scikit-learn = ">=1.5.2,<2"
pyarrow = ">=13.0.0,<14"
numpy = "<2"
cudatoolkit = "11.8"
omegaconf = ">=2.3.0,<3"
wandb = ">=0.17.3,<0.18"
pip = ">=25.2,<26"
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.30.1,<7"
seaborn = ">=0.13.2,<0.14"
transformers = ">=4.55.4,<5"
shap = ">=0.48.0,<0.49"

[pypi-dependencies]
torch = ">=2.6"
torchvision = "*"
torchaudio = "*"
pytorch-lightning = ">=2.4.0,<3"
torch-geometric = "*"
deepchem = "*"
bertviz = "*"
xgboost = ">=2.1.1,<3"

[target.linux-64.dependencies]
cudatoolkit = "11.8"

[system-requirements]
libc = { family = "glibc", version = "2.26" }
cuda = "11.8"
